-- package
insert into package (oid, name, package_json, description, price, period, package_type) values ('P-Free','Free','[{"module":"Customer","noOfEntry":1},{"module":"Passport","noOfEntry":10},{"module":"Vendor","noOfEntry":2},{"module":"User","noOfEntry":1}]','Free','Free','Lifetime','Default');
insert into package (oid, name, package_json, description, price, period, package_type) values ('P-Lite','Lite','[{"module":"Customer","noOfEntry":50},{"module":"Passport","noOfEntry":500},{"module":"Vendor","noOfEntry":50},{"module":"User","noOfEntry":5}]','Lite','500','Monthly','Default');
insert into package (oid, name, package_json, description, price, period, package_type) values ('P-Standard','Standard','[{"module":"Customer","noOfEntry":100},{"module":"Passport","noOfEntry":1000},{"module":"Vendor","noOfEntry":"Unlimited"},{"module":"User","noOfEntry":"Unlimited"}]','Standard','1000','Monthly','Default');
insert into package (oid, name, package_json, description, price, period, package_type) values ('P-Enterprise','Enterprise','[{"module":"Customer","noOfEntry":"Unlimited"},{"module":"Passport","noOfEntry":"Unlimited"},{"module":"Vendor","noOfEntry":"Unlimited"},{"module":"User","noOfEntry":"Unlimited"}]','Enterprise','3000','Monthly','Default');
insert into package (oid, name, package_json, description, price, period, package_type) values ('P-Custom','Custom','[{"module":"Customer","noOfEntry":"Negotiable"},{"module":"Passport","noOfEntry":"Negotiable"},{"module":"Vendor","noOfEntry":"Negotiable"},{"module":"User","noOfEntry":"Negotiable"}]','Custom','Negotiable','Monthly','Default');
commit;

-- company
insert into company (oid, mnemonic, name, short_name, company_json, address, status, logo_path) values ('C-GTA','GTA','Global Travel Advantage','gta','{"email_config":{"email_id":"ticlgta000001@gmail.com","email_password":"ticl@321#"},"base_directory" : "/data/gds/data/gta"}','ZAMAN TOWER, LEVEL - 12, 1202, 37-2, PURANA PALTAN, 
CULVERT RD ,DHAKA, BANGLADESH.
TELEPHONE: 02-47124334/01671123144
EMAIL:     INFO@GTABD.COM','Active','gta_logo.png');
insert into company (oid, mnemonic, name, short_name, company_json, address, status, logo_path) values ('C-HTT','hornbillttl','Hornbill Tours and Travels','htt','{"email_config":{"email_id":"ticlhornbil000002@gmail.com","email_password":"ticl@321#"},"base_directory" : "/data/gds/data/htt"}','House: GA93 (3rd Floor), Gulshan-Badda Link Road, 
Middle Badda, Dhaka-1212
Phone: +88-02-8837010','Active','hornbill_logo.jpg');
insert into company (oid, mnemonic, name, short_name, company_json, address, status, logo_path) values ('C-DEMO','demo','Demo','demo','{"email_config":{"email_id":"ticl7861@gmail.com","email_password":"technoinnovators786"},"base_directory" : "/data/gds/data/demo"}','Dhaka','Active','hornbill_logo.jpg');
commit;

-- department
insert into department (oid, name, sort_order, company_oid) values ('Dept-Fin','Finance',1,'C-DEMO');
insert into department (oid, name, sort_order, company_oid) values ('Dept-NOC','NOC',2,'C-DEMO');
insert into department (oid, name, sort_order, company_oid) values ('Dept-SCC','Service & Customer Care',3,'C-DEMO');
insert into department (oid, name, sort_order, company_oid) values ('Dept-Mar','Marketing',4,'C-DEMO');
insert into department (oid, name, sort_order, company_oid) values ('Dept-Net','CM Network',5,'C-DEMO');
insert into department (oid, name, sort_order, company_oid) values ('Dept-Soft','Web and Software',6,'C-DEMO');
insert into department (oid, name, sort_order, company_oid) values ('Dept-Adm','Administration',7,'C-DEMO');
commit;

-- designation
insert into designation (oid, name, sort_order, company_oid) values ('Des-GM','GM',1,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-AGM','AGM',2,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-AM','Asst. Manager',3,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-DM','Dty. Manager',4,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-SE','Sr. Executive',5,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-SME','Sr. Mkt Executive',6,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-EXE','Executive',7,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-ENG','Engineer',8,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-SADM','System Admin',9,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-TEC','Technician',10,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-ELE','Electrician',11,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-COL','Collection',12,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-JEXE','Jr.  Executive',13,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-ASADM','Asst. Sys Admin',14,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-JSENG','Jr. Support Engr.',15,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-AA','Admin Asst.',16,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-AT','Asst. Technician',17,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-DRI','Driver',18,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-PEO','Peon',19,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-OA','Office Assistant',20,'C-DEMO');
insert into designation (oid, name, sort_order, company_oid) values ('Des-COO','Cook',21,'C-DEMO');
commit;

-- bank_account
insert into bank_account (oid, account_no, account_name, branch_name, initial_balance, status, created_by, bank_oid, company_oid) values ('ba-demo','3784762184','Demo','Shaymoli Branch',0,'Active','demo','Bank-1016','C-DEMO');
commit;

-- people
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-001','REGENT AIRWAYS','028919117','info@gtabd.com','siaam tower level 7 plot 15 road 2 sector 3 uttara model town dhaka 1230','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-002','IndiGo','8801617224404','reservations@goindigo.in','MTIAZ AHMED
Senior Executive (Sales)
Renaissance Aviation Services Limited

Tel : +88 02 9883374, +88 02 9890378
8801617-224404','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-003','DRUK AIR','01715593852','kamrul_azmary@yahoo.com','RESERVATION OFFICER','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-004','BIMAM BANGLADESH AIRLINES','029560151','info@gtabd.com',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-005','HALTRIP','8809611333888','info@altrip.com',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-006','IATA','01915529412','iata@iata.org',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-007','CHALLENGER TRAVELS & TOURS LTD','028311685/58312574/9340271, 01711140377','challengertravels@gmail.com','city heart building 5 th floor 67 nayapaltan dhaka-1000','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-008','Jetstar Airways Pty Ltd','65654465','sales@jetstar.com',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-009','HORNBILL TRAVELS AND TOURS','01731953246','info@gtabd.com','GULSHAN BADDA LINK ROAD','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-010','GLOBAL TRAVEL ADVANGE','01552565717','info@gtabd.com','zaman tower lavel-12 37/2 purana paltan culvert road dhaka-1000','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-011','US-Bangla Airlines','8801777777800','crc@us-banglaairlines.com','House-77, Sohrawardi Avenue, Baridhara Diplomatic Zone
Dhaka-1212, Bangladesh','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-012','THAI LION AIRLINES','0255042000','travelagent@lionairthai.com',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-013','MALINDO AIR','01762684094','tahijb@tuneglobal.com','5th floor,modhumoti plaza concord plot no.11,Block G Banani,Dhaka 1213,Bangladesh','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-014','AirAsia','01732560570','delwar.airasia@gmail.com',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-015','NOVO-AIR','13603','info@flynovoair.com',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-016','CHALLENGER TRAVELS & TOURS LTD','028311685/58312574/9340271, 01711140377','challengertravels@gmail.com','city heart building 5 th floor 67 nayapaltan dhaka-1000','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-017','MALDIVIAN AIRLINES (Q2) GSA GALAXY AIR','029849711','maldivian@airgalaxy.com.bd','TAJ KASILINA GULSHAN 1  
AIR GALAXY LTD A/C NO 00433010366  BANK ASIA LTD','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-018','AL GAZI TRAVELS LTD','9567168','algazi2050@gmail.com',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-019','Hajee Air Travel','8801926993230','hajee_accounts@hotmail.com','dhaka','["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-020','Hajee Air Travels Ltd','9342446','hajeeair@hotmail.com',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-021','Haltrip Travels','58317080','support@haltrip.com',null,'["Supplier"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-022','Maliha Yeasmin Nomi','01674745987','maliha.nomi@gtabd.com','Eastern Panaroma,#1203, 3/2 Topkhana Road, Dhaka-1000','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-023','MOHAMMAD MUSTAFIZUR RAHMAN','01552565717','GTA18052202@GTABD.COM',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-024','MOHAMMED SHAHADAT','01711544281','SNENT12@YAHOO.COM','KHILGONG,ROAD 21,DHAKA,1219','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-025','MOBARAK HOSSAIN','01819203553','GTA18051504@GTABD.COM',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-026','MD AKRAM HOSSAIN','01832897936','GTA18052201@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-027','MD ABU TALEB','01819133896','GTA18052301@GTABD.COM',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-028','ABDUL ALIM','01552638663','ABDULALIM@GTABD.COM','116,SEGUN BAGICHA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-029','IMAM MD MAZHARUL (SINA)','01611522742','sina7000@hotmail.com','IDB bhobon','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-030','MR TABARAK HOSSAIN','01762366171','namirasteelbd@gmail.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-031','Mahmud Imtiaz','01917282444','GTA18050101@gtabd.com','pankouri','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-032','MOHAMMAD SALIM','01552565717','MOHAMMAD.SALIM@GTABD.COM','EASTERN PANAROMA, 3/2 TOPKHANA ROAD, SHAHBAGH DHAKA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-033','HOWLADER ZAINAL ABEDIN','01754777788','VISIONEXPRESSBD@GMAIL.COM','BASHUNDHARA CITY LEVEL 5 BLOCK D SHOP 61,62,63','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-034','SHEIKHNURUL ISLAM','01911360622, 01765541455','GTA18051505@GTABD.COM',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-035','NAZMUL HAQUE','01712790319','GTA18051503@GTABD.COM',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-036','SAYED RIPAN MIA','01761886347','INFO@GTABD.COM','HOUSE-09,ROAD-11,SECTOR-11,UTTARA,UTTARA WEST,DHAKA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-037','SHEIKH MOTALEB','01629103123','GTA18051502@GTABD.COM','FARAMGATE','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-038','MOHAMMAD JANE','01911492872','INFO@GTABD.COM','25/1,HOSSEN UDDIN KHAN,LALBAGH,LALBAGH,DHAKA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-039','XXXXX','01819745556','sharafathossain786@gmail.com','Dhaka','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-040','MOTIUR RAHMAN','01552767892','INFO@GTABD.COM','KHAL IFAPATTI,MOHANGANJ,MOHANGANJ,NETROKONA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-041','MD KHORSHED ALAM','01713038259','nabarupa.bd@gmail.com','270/1 ELEPHANT ROAD DHAKA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-042','MD BABUL','88001711530733','GTACT201807190001@GTABD.COM',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-043','AKHTER RABEYA','01761493933','dreammyrose76@gmail.com','Dhanmondi','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-044','MOHAMMAD ABDUL KADIR RUBEL','01712173798','INFO@GTABD.COM',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-045','MD MOTIUR RAHMAN ANIK ELECTRONICS','01534209327','INFO@GTABD.COM','ANIK ELECTRONICS BAYTUL MOKARRAM MARKET, DHAKA 1000','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-046','MD FAZLUL KARIM SAJAL','01714182700','INFO@GTABD.COM','TRILLOCHANPUR,SHONAPUR,BALIAKANDI,RAJBARI','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-047','RYHAN UDDIN','01717055871','ryhan.uddin@gmail.com','KALABAGAN','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-048','ZAINAL ABEDIN HOWLADER','01754777788','delete@delete.com','BASHUNDHARA CITY SHOPPING MALL,
LEVEL-5,BLOCK-D,SHOP-61,62,63,
PANTHAPATH,DHAKA-1215','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-049','M A HANNAN AZAD','01711530475','INFO@GTABD.COM','ALNKAR NIKETON 
BOSUNDHARA CITY,DHAKA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-050','TAHNAN AL ANAS','01671123144','TAHNAN.ANAS@GTABD.COM','45 LALIT MOHONDASH LANE','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-051','MAMUNUR RASHID','01771401822','INFO@GTABD.COM','SHANTI NAGAR DHAKA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-052','MOTIUR RAHMAN USA','01552576717','INFO@GTABD.COM','LAX USA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-053','MOHAMMAD BONY TASNIM IBNA RAZZAK','01844074011','BONY.TASNIM@GMAIL.COM','THAKAR GAON','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-054','AL KUDDUS TRAVELS','01711457886','alkuddushabigonj@gmail.com','HOBIGANG,SYLHET','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-055','KHAN SARAFAT HOSSAIN','01711381619','SARAFATBADAL@GMAIL.COM','HOUSE 16, WEST NAKHALPARA, TEJGAON','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-056','BABUL KARMAKAR','01680503188','INFO@GTABD.COM',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-057','MD MONIRUZZAMAN','01534530467','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-058','ABDUL HALIM','01670789510','HSMULTITRADE@YAHOO.COM','SAGUN BAGHICHA CONCORD. FLAT 18 A,
5,SAGUN BAGHICHA,DHAKA 1000','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-059','RAZIB','01819167606, 01777390369','SHARIFOPTICS@GMAIL.COM','FARMGATE','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-060','MD SAIDUL ALAM','01720050241','INFO@GMAIL.COM','HAJI ISLAM MARKET,(1ST FLOOR)1,PATUATULY LANE,DHAKA-1100 PHONE:OFF : 02-7394081','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-061','MOHAMMAD NASIRUDDIN','01819505307','RAHAMANIA.BD@GMAIL.COM','HOUSE 16 KULAL MAHAL LANE, JIGATALA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-062','md alamgir kabir','01552321384','asaautoaccessories@hotmail.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-063','ALI HOSSAIN/ALI OPTICS','01819487142, 01557385350','ali.hossain_optics@yahoo.com','EASTERN PANAROMA, #602, 3/2 TOPKHANA ROAD, DHAKA-1000','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-064','ARAFAT NOOR KAFI','01552601037','arafatnoor.kafi@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-065','ABDULLAH/KHALED','01711082454','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-066','TUSHAR GOSH','01914354559','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-067','ABDUS SALAM City Plastic','01911348715','INFO@GTABD.COM','21 NO NILAMBAR,SHAHA ROAD,NEW MARKET,HAZARIBAGH,DHAKA.TELEPHONE NO:9668983','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-068','NAZMUL HASAN','01728744101','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-069','MD SHARAFAT HOSSAIN KAMAL','01819745556','sharafathossain786@gmail.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-070','MR ABDUS SALAM KHAN','01710955900','asalamkhan649@gmai.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-071','MOHAMMAD MONIRUZZAMAN RONY','01910100180','moniruzzamanrony47@gmail.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-072','ABDUS SALAM casuin','01819295048','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-073','GENERAL OFFICE ID','01704170300','.ticket@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-074','YOUNUS/MD','01815443150','younus_eyetouch@yahoo.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-075','NOSHIN YEASMIN SONAM','0091981830498','sonam.aust@gmai.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-076','MOHAMMAD RAZU','01822776633/01942266555','rajuenterprise6633@gmail.com','MAA SHA ALLAH razu parlour gallery
HAZI JANE-E-ALAM MARKET 38 MUKIM KATARA MOULVI BAZAR DHAKA-1100 shop# 2','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-077','MD SHARIFUL ISLAM','0191130886','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-078','GOLAM MOSTAFA MD SHAKIL','01704170306','gm.shakil@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-079','TANVIR ISLAM MURAD','01852530555','masumg@hotmail.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-080','MD ABU KALAM','01715474165','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-081','Shafiulazam Chowdhury','01977400848','s.chowdhury@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-082','TANVIR HASSAN','01819434650','tanvir.rmia@gmail.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-083','DR SHERIF MUHAMMAD ALAMGIR','01670565621','Iinfo@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-084','JAHIDUR RAHMAN ROBIN','0171','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-085','HAJI HAFEZ MOHAMMAD ANISUR RAHMAN','01','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-086','Doer Services limited','01844074011','bony.tasnim@doer.com.bd','SunMoon Star Tower (L-11), 37 Dilkusha, Dhaka-1000','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-087','MD FARID UDDIN','01615707079','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-088','MD ABDUR RAZZAK','01760100047','info@gtabd.com','FRIENDS VISION PATUATULI DHAKA','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-089','MD MOMIN UDDIN SUMAN','xxxxxxxxxxxx','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-090','IMRAN HOSSAIN','01716818889','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-091','SHEIKH SADEQUL HUDA','01712915510','info@gtabd.com','noor optical company  patuatuli dhaka','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-092','K M KAMRUZZAMAN SABUJ','01735151095','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-093','MD MASUD REZA','01620448496','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-094','MD AMINUL ISLAM POLAS','xxxxxxxxxxxx','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-095','MR.MD KHLLIUR RAHMAN','01911588112','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-096','MD AKTER HOSSAIN','01842477178','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-097','MIZAN SHEIK','01998831403','GTACT201905210001@GTABD.COM',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-098','MD BADIUZZAMAN KHOKAN KHOKAN','01681297381','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-099','KAZI BAPPI SAGAR','01785905046/01615905046','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-100','MD SHAHIDUL ISLAM PIKLU','01552565717','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-101','MOHAMMAD NAZMUL HAQUE','01919126086','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-102','MR MIRAZ','01912114922','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-103','NARAYON CHANDRA SAHA','xxxxxxxxxxxx','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-104','MD AMINUL ISLAM KAJAL','xxxxxxxxxxxxx','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-105','HORNBILL TRAVELS & TOURS LTD','01731953246','hornbill.ttl@gmail.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-106','MD RUHUL AMIN SARKER','01678004552','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-107','MD BADIUZZMAN','01552565717','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-108','MD SHARIF','01558540300','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-109','KERANIGONJ TRADING','01711529254','keranigongtrading@gmail.com','chawk mogultully,dhaka-1211','["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-110','KALAM ENTERPRISE','01715474165','info@gtabd.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-111','LUTHFOR RAHMAN','01911191183','lrahman_5@yahoo.com',null,'["Customer"]','Active',null,null,'C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-112','Debbrota Laha',null,null,null,'["Employee"]','Active','Dept-Fin','Des-GM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-113','Md. Yunus Ali',null,null,null,'["Employee"]','Active','Dept-Fin','Des-AGM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-114','Md. Monirul Islam',null,null,null,'["Employee"]','Active','Dept-Fin','Des-SE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-115','Madhu Shudan Mrida',null,null,null,'["Employee"]','Active','Dept-Fin','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-116','Alamgir Morshed Bhuiyan',null,null,null,'["Employee"]','Active','Dept-Fin','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-117','Rumana Ramjaan',null,null,null,'["Employee"]','Active','Dept-Fin','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-118','Sharmin Akhter',null,null,null,'["Employee"]','Active','Dept-Fin','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-119','Apu Kumar Kundu',null,null,null,'["Employee"]','Active','Dept-Fin','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-120','Mostafezur Rahman',null,null,null,'["Employee"]','Active','Dept-Fin','Des-AGM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-121','Hossain Ahmed Sajal',null,null,null,'["Employee"]','Active','Dept-Fin','Des-JEXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-122','Mohammad Ziauddin',null,null,null,'["Employee"]','Active','Dept-Fin','Des-AM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-123','Selimujjaman',null,null,null,'["Employee"]','Active','Dept-Fin','Des-COL','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-124','Mithu Laha',null,null,null,'["Employee"]','Active','Dept-Fin','Des-JEXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-125','Md. Masud Parvez Limon',null,null,null,'["Employee"]','Active','Dept-NOC','Des-SADM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-126','Md. Tahnan Al Anas',null,null,null,'["Employee"]','Active','Dept-NOC','Des-ASADM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-127','Md. Imran Hossain',null,null,null,'["Employee"]','Active','Dept-NOC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-128','Ryhan Uddin',null,null,null,'["Employee"]','Active','Dept-NOC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-129','Md. Mofazzal Hossain',null,null,null,'["Employee"]','Active','Dept-SCC','Des-AM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-130','Mustafizur Rahman',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-131','Md. Mohsin',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-132','Md. Anisuzzaman Faysal',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-133','Azizul Huq',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-134','Mahbubur Rahman',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-135','Habiba Yasmin',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-136','Md. Sohel Rana',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-137','Md. Soliman',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-138','Anisur Rahman Bappy',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-139','Miladul Islam',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-140','Asaduzzaman',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-141','Saiful Islam',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-142','Mr. Shafiur Rahman',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-143','Md. Ishtiuq Hossain',null,null,null,'["Employee"]','Active','Dept-SCC','Des-JSENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-144','Md. Abu Taher',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-145','Abdus Samad Mondol',null,null,null,'["Employee"]','Active','Dept-SCC','Des-ENG','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-146','Ruhul Amin Fakir',null,null,null,'["Employee"]','Active','Dept-Mar','Des-AGM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-147','Khurshid Mehboob',null,null,null,'["Employee"]','Active','Dept-Mar','Des-DM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-148','Mr. Mominul Haque',null,null,null,'["Employee"]','Active','Dept-Mar','Des-SME','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-149','Md. Maksuduzzaman',null,null,null,'["Employee"]','Active','Dept-Mar','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-150','Mohasin Ahmned Tuhin',null,null,null,'["Employee"]','Active','Dept-Mar','Des-AM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-151','Md. Golam Rabbany',null,null,null,'["Employee"]','Active','Dept-Mar','Des-AM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-152','Shakila Chowdhury',null,null,null,'["Employee"]','Active','Dept-Mar','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-153','Mahfuzur Rahman',null,null,null,'["Employee"]','Active','Dept-Mar','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-154','Aminul Haque',null,null,null,'["Employee"]','Active','Dept-Mar','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-155','Mahenoor Quraishi',null,null,null,'["Employee"]','Active','Dept-Mar','Des-DM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-156','Abdul Matin Mia',null,null,null,'["Employee"]','Active','Dept-Net','Des-TEC','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-157','Abdul Matin (2)',null,null,null,'["Employee"]','Active','Dept-Net','Des-TEC','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-158','Sudorshan Rema',null,null,null,'["Employee"]','Active','Dept-Net','Des-ELE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-159','Uzzal Gomes',null,null,null,'["Employee"]','Active','Dept-Net','Des-ELE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-160','Julhash Mia',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-161','Md. Kawsar',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-162','Jashim Uddin',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-163','Md. Nasim',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-164','Md. Alamin',null,null,null,'["Employee"]','Active','Dept-Net','Des-DRI','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-165','Md. Shahjahan',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-166','Md. Nazrul Islam',null,null,null,'["Employee"]','Active','Dept-Net','Des-TEC','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-167','Akhter Hossain',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-168','Md. Abdul Mazed',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-169','Imam Sheikh',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-170','Rafiul Islam',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-171','Md. Zakaria',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-172','Mithu Gomes',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-173','Md. Abdul Khalek',null,null,null,'["Employee"]','Active','Dept-Net','Des-AT','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-174','Md. Faizul Kabir',null,null,null,'["Employee"]','Active','Dept-Soft','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-175','Ruhul Amin Sarker',null,null,null,'["Employee"]','Active','Dept-Adm','Des-GM','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-176','Inzamamul Islam Sazal',null,null,null,'["Employee"]','Active','Dept-Adm','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-177','Sumona Akhter',null,null,null,'["Employee"]','Active','Dept-Adm','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-178','Ishrat Jahan',null,null,null,'["Employee"]','Active','Dept-Adm','Des-EXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-179','Shahidun Nabi',null,null,null,'["Employee"]','Active','Dept-Adm','Des-DRI','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-180','Abul Hossain',null,null,null,'["Employee"]','Active','Dept-Adm','Des-AA','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-181','Leonardo Rechil',null,null,null,'["Employee"]','Active','Dept-Adm','Des-PEO','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-182','Md. Alam',null,null,null,'["Employee"]','Active','Dept-Adm','Des-DRI','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-183','Md. Jahangir',null,null,null,'["Employee"]','Active','Dept-Adm','Des-JEXE','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-184','Md. Shah Alam',null,null,null,'["Employee"]','Active','Dept-Adm','Des-DRI','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-185','Rani Begum',null,null,null,'["Employee"]','Active','Dept-Adm','Des-OA','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-186','Ms. Nasima',null,null,null,'["Employee"]','Active','Dept-Adm','Des-COO','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-187','Md. Ripon Sarker',null,null,null,'["Employee"]','Active','Dept-Adm','Des-DRI','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-188','Md. Mominul Islam',null,null,null,'["Employee"]','Active','Dept-Adm','Des-DRI','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-189','Md. Ershad',null,null,null,'["Employee"]','Active','Dept-Adm','Des-OA','C-DEMO');
insert into people (oid, name, mobile_no, email, address, people_type, status, department_oid, designation_oid, company_oid) values ('P-190','Riazul Islam',null,null,null,'["Employee"]','Active','Dept-Adm','Des-AM','C-DEMO');
commit;


