-- role
insert into role (oid, role_id, role_description, menu_json, report_json, status) values ('superadmin','superadmin','Super Admin','[]','[]','Active');
insert into role (oid, role_id, role_description, menu_json, report_json, status) values ('admin','admin','admin','[{"path":"/dashboard","icon":"home","text":"Dashboard"},{"path":"/people/people-list","icon":"usergroup-add","text":"People"},{"path":"/bank","icon":"bank","text":"Bank","submenus":[{"path":"/bank/bank-account-list","icon":"account-book","text":"Bank Account"},{"path":"/bank/bank-transaction","icon":"transaction","text":"Bank Transaction"}]},{"path":"/inventory","icon":"bar-chart","text":"Inventory","submenus":[{"path":"/inventory/warehouses-list","icon":"shop","text":"Warehouse"},{"path":"/inventory/product-unit-list","icon":"calculator","text":"Product Unit"},{"path":"/inventory/product-categories-list","icon":"check-square","text":"Product Category"},{"path":"/inventory/products","icon":"project","text":"Product"}]},{"path":"/accounting","icon":"calculator","text":"Accounting","submenus":[{"path":"/accounting/chart-of-accounts","icon":"line-chart","text":"Chart of Account"},{"path":"/accounting/ledger-subgroup","icon":"block","text":"Ledger Subgroup"},{"path":"/accounting/ledger-setting","icon":"setting","text":"Ledger Setting"},{"path":"/accounting/manual-journal","icon":"solution","text":"Manual Journal"},{"path":"/accounting/financial-period","icon":"field-time","text":"Financial Period"}]},{"path":"/expense","icon":"dollar","text":"Expense","submenus":[{"path":"/expense/expense-list","icon":"dollar","text":"Expense List"}]},{"path":"/cash-book","icon":"book","text":"Cashbook","submenus":[{"path":"/cash-book/cash-book-list","icon":"book","text":"Cashbook List"}]},{"path":"/payment","icon":"dollar","text":"Payment","submenus":[{"path":"/payment/payment-made","icon":"import","text":"Payment Made"},{"path":"/payment/payment-receive","icon":"export","text":"Payment Receive"}]},{"path":"/credit","icon":"fund","text":"Credit","submenus":[{"path":"/credit/credit-note","icon":"form","text":"Credit Note"},{"path":"/credit/vendor-credit","icon":"account-book","text":"Vendor Credit"}]},{"path":"/refund","icon":"left-square","text":"Refund","submenus":[{"path":"/refund/refund-credit-note","icon":"rollback","text":"Credit Note Refund"},{"path":"/refund/vendor-credit-refund","icon":"rollback","text":"Vendor Credit Refund"}]},{"path":"/adjust","icon":"retweet","text":"Adjust","submenus":[{"path":"/adjust/credit-note-adjust","icon":"box-plot","text":"Credit Note Adjust"},{"path":"/adjust/vendor-credit-adjust","icon":"box-plot","text":"Vendor Credit Adjust"}]},{"path":"/invoice","icon":"container","text":"Invoice"},{"path":"/activity","icon":"alert","text":"Activity"},{"path":"/report/report","icon":"file-text","text":"Report"}]','[]','Active');
insert into role (oid, role_id, role_description, menu_json, report_json, status) values ('customer','customer','Customer','[]','[]','Active');
insert into role (oid, role_id, role_description, menu_json, report_json, status) values ('supplier','supplier','Supplier','[]','[]','Active');
commit;

-- login
insert into login (oid, login_id, password, name, image_path, status, role_oid, company_oid) values ('sa','sa','sa','Super Admin',null,'Active','superadmin',null);
insert into login (oid, login_id, password, name, image_path, status, role_oid, company_oid) values ('admin','admin','sa','Admin',null,'Active','admin','C-DEMO');
commit;


