-- thana
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-1','1','Demra','ডেমরা','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-10','10','Khilkhet','খিলক্ষেত','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-100','100','Belabo','বেলাব','Dist-12');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-101','101','Monohordi','মনোহরদী','Dist-12');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-102','102','Narshingdi Sadar','নরসিংদী সদর','Dist-12');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-103','103','Palash','পলাশ','Dist-12');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-104','104','Raypura','রায়পুরা','Dist-12');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-105','105','Shibpur','শিবপুর','Dist-12');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-106','106','Susung Durgapur','সুসুংদুর্গাপুর','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-107','107','Atpara','আটপাড়া','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-108','108','Barhatta','বারহাট্টা','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-109','109','Dharmapasha','ধর্মপাশা','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-11','11','Lalbag','লালবাগ','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-110','110','Dhobaura','ধবাউরা','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-111','111','Kalmakanda','কলমাকান্দা','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-112','112','Kendua','কেন্দুয়া','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-113','113','Khaliajuri','খালিয়াজুরী','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-114','114','Madan','মদন','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-115','115','Moddhynagar','মধ্য নগর','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-116','116','Mohanganj','মোহনগঞ্জ','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-117','117','Netrakona Sadar','নেত্রকোণা সদর','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-118','118','Purbadhola','পূর্বধলা','Dist-13');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-119','119','Baliakandi','বালিয়াকান্দি','Dist-14');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-12','12','Mirpur','মিরপুর','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-120','120','Pangsha','পাংশা','Dist-14');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-121','121','Rajbari Sadar','রাজবাড়ী সদর','Dist-14');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-122','122','Bhedorganj','ভেদরগাঞ্জ','Dist-15');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-123','123','Damudhya','ডামুড্যা','Dist-15');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-124','124','Gosairhat','গোসাইরহাট','Dist-15');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-125','125','Jajira','জাঁজিরা','Dist-15');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-126','126','Naria','নড়িয়া','Dist-15');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-127','127','Shariatpur Sadar','শরীয়তপুর সদর','Dist-15');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-128','128','Bakshigonj','বাকশিগঞ্জ','Dist-16');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-129','129','Jhinaigati','ঝিনাইগাতী','Dist-16');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-13','13','Mohammadpur','মোহাম্মদপুর','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-130','130','Nakla','নকলা','Dist-16');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-131','131','Nalitabari','নালিতাবাড়ী','Dist-16');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-132','132','Sherpur Shadar','শেরপুর সদর','Dist-16');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-133','133','Shribardi','শ্রীবর্দী','Dist-16');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-134','134','Basail','বাসাইল','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-135','135','Bhuapur','ভূঞাপুর','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-136','136','Delduar','দেলদুয়ার','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-137','137','Ghatail','ঘাটাইল','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-138','138','Gopalpur','গোপালপুর','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-139','139','Kalihati','কালিহাতী','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-14','14','Motijheel','মতিঝিল','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-140','140','Kashkaolia','কাশকাওলিয়া','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-141','141','Madhupur','মধুপুর','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-142','142','Mirzapur','মির্জাপুর','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-143','143','Nagarpur','নাগরপুর','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-144','144','Sakhipur','সখীপুরে','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-145','145','Tangail Sadar','টাঙ্গাইল সদর','Dist-17');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-146','146','Alikadam','আলিকদম','Dist-18');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-147','147','Bandarban Sadar','বান্দরবান সদর','Dist-18');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-148','148','Naikhong','নাইখং','Dist-18');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-149','149','Roanchhari','রয়াঞ্ছহারি','Dist-18');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-15','15','Nawabganj','নবাবগঞ্জ','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-150','150','Ruma','রুমা','Dist-18');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-151','151','Thanchi','থানচি','Dist-18');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-152','152','Akhaura','আখাউড়া','Dist-19');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-153','153','Banchharampur','বাঞ্ছারামপুর','Dist-19');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-154','154','Brahamanbaria Sadar','ব্রাহ্মণবাড়িয়া সদর','Dist-19');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-155','155','Kasba','কসবা','Dist-19');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-156','156','Nabinagar','নবীনগর','Dist-19');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-157','157','Nasirnagar','নাসিরনগর','Dist-19');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-158','158','Sarail','সরাইল','Dist-19');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-159','159','Chandpur Sadar','চাঁদপুর সদর','Dist-20');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-16','16','New market','নতুন বাজার','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-160','160','Faridganj','ফরিদগঞ্জ','Dist-20');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-161','161','Hajiganj','হাজীগঞ্জ','Dist-20');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-162','162','Hayemchar','হায়েমছর','Dist-20');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-163','163','Kachua','কচুয়া','Dist-20');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-164','164','Matlobganj','মতলব গঞ্জ','Dist-20');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-165','165','Shahrasti','শাহরাস্তি','Dist-20');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-166','166','Anawara','আনোয়ারা','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-167','167','Boalkhali','বোয়ালখালী','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-168','168','Chittagong Sadar','চট্টগ্রাম সদর','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-169','169','East Joara','পূর্ব জয়ারা','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-17','17','Palton','পল্টন','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-170','170','Fatikchhari','ফটিকছড়ি','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-171','171','Hathazari','হাটহাজারী','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-172','172','Jaldi','জলদি','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-173','173','Lohagara','লোহাগাড়া','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-174','174','Mirsharai','মীরসরাই','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-175','175','Patia Head Office','পটিয়ার প্রধান কার্যালয়','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-176','176','Rangunia','রাঙ্গুনিয়া','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-177','177','Rouzan','রউযান','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-178','178','Sandwip','সন্দ্বীপ','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-179','179','Satkania','সাতকানিয়া','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-18','18','Ramna','রমনা','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-180','180','Sitakunda','সীতাকুন্ড','Dist-21');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-181','181','Barura','বরুড়া','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-182','182','Brahmanpara','ব্রাহ্মণপাড়া','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-183','183','Burichang','বুড়িচং','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-184','184','Chandina','চান্দিনা','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-185','185','Chouddagram','চৌদ্দগ্রাম','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-186','186','Comilla Sadar','কুমিল্লা সদর','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-187','187','Daudkandi','দাউদকান্দি','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-188','188','Davidhar','দাভিধার','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-189','189','Homna','হোমনা','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-19','19','Sabujbag','সবুজবাগ','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-190','190','Laksam','লাকসাম','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-191','191','Langalkot','নাঙ্গলকোট','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-192','192','Muradnagar','মুরাদনগর','Dist-22');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-193','193','Chiringga','ছিরিংগা','Dist-23');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-194','194','Coxs Bazar Sadar','কক্সবাজার সদর','Dist-23');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-195','195','Gorakghat','গরাকঘাট','Dist-23');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-196','196','Kutubdia','কুতুবদিয়া','Dist-23');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-197','197','Ramu','রামু','Dist-23');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-198','198','Teknaf','টেকনাফ','Dist-23');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-199','199','Ukhia','উখিয়া','Dist-23');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-2','2','Dhaka Cantt.','ঢাকা ক্যন্টনমেন্ট.','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-20','20','Savar','সাভার','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-200','200','Chhagalnaia','ছাগলনাইয়া','Dist-24');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-201','201','Dagonbhuia','দাগনভুইয়া','Dist-24');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-202','202','Feni Sadar','ফেনী সদর','Dist-24');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-203','203','Pashurampur','পরশুরাম্পুর','Dist-24');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-204','204','Sonagazi','সোনাগাজী','Dist-24');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-205','205','Diginala','দিগিনালা','Dist-25');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-206','206','Khagrachari Sadar','খাগড়াছড়ি সদর','Dist-25');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-207','207','Laxmichhari','লাক্সিছড়ি','Dist-25');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-208','208','Mahalchhari','মাহালছড়ি','Dist-25');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-209','209','Manikchhari','মানিকছড়ি','Dist-25');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-21','21','Sutrapur','সুত্রাপুর','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-210','210','Matiranga','মাটিরাঙ্গা','Dist-25');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-211','211','Panchhari','পানছড়ি','Dist-25');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-212','212','Ramghar Head Office','রামগড়ে প্রধান কার্যালয়','Dist-25');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-213','213','Char Alexgander','চর আলেকজান্ডার','Dist-26');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-214','214','Lakshimpur Sadar','লক্ষ্মীপুর সদর','Dist-26');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-215','215','Ramganj','রামগঞ্জ','Dist-26');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-216','216','Raypur','রায়পুর','Dist-26');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-217','217','Basurhat','বাসুরহাট','Dist-27');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-218','218','Begumganj','বেগমগঞ্জ','Dist-27');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-219','219','Chatkhil','চাটখিল','Dist-27');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-22','22','Tejgaon','তেজগাঁও','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-220','220','Hatiya','হাতিয়া','Dist-27');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-221','221','Noakhali Sadar','নোয়াখালী সদর','Dist-27');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-222','222','Senbag','সেনবাগ','Dist-27');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-223','223','Barakal','বারাকাল','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-224','224','Bilaichhari','বিলাইছড়ি','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-225','225','Jarachhari','জরছড়ি','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-226','226','Kalampati','কালাম্পাতি','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-227','227','kaptai','কাপ্তাই','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-228','228','Longachh','লঙ্গাছ','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-229','229','Marishya','মারিশ্যা','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-23','23','Tejgaon Industrial Area','তেজগাঁও শিল্প এলাকা','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-230','230','Naniachhar','নানিয়াছর','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-231','231','Rajsthali','রাজস্থালি','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-232','232','Rangamati Sadar','রাঙ্গামাটি সদর','Dist-28');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-233','233','Alamdanga','আলমডাঙ্গা','Dist-29');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-234','234','Chuadanga Sadar','চুয়াডাঙ্গা সদর','Dist-29');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-235','235','Damurhuda','দামুড়হুদা','Dist-29');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-236','236','Doulatganj','দোলতগাগঞ্জ','Dist-29');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-237','237','Bagerhat Sadar','বাগেরহাট সদর','Dist-30');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-238','238','Chalna Ankorage','চালনা Ankorage','Dist-30');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-239','239','Chitalmari','চিতলমারী','Dist-30');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-24','24','Uttara','উত্তরা','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-240','240','Fakirhat','ফকিরহাট','Dist-30');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-241','241','Kachua UPO','কচুয়া ইউ পি ও','Dist-30');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-242','242','Mollahat','মোল্লাহাট','Dist-30');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-243','243','Morelganj','মোরেলগঞ্জের','Dist-30');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-244','244','Rampal','রামপাল','Dist-30');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-245','245','Rayenda','রায়েন্দা','Dist-30');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-246','246','Bagharpara','বাঘারপাড়া','Dist-31');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-247','247','Chaugachha','চৌগাছা','Dist-31');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-248','248','Jessore Sadar','যশোর সদর','Dist-31');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-249','249','Jhikargachha','ঝিকরগাছা','Dist-31');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-25','25','Alfadanga','আলফাডাঙ্গা','Dist-2');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-250','250','Keshabpur','কেশবপুর','Dist-31');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-251','251','Monirampur','মনিরামপুর','Dist-31');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-252','252','Noapara','নোয়াপাড়া','Dist-31');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-253','253','Sarsa','শার্শা','Dist-31');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-254','254','Harinakundu','হরিনাকুন্ডু','Dist-32');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-255','255','Jinaidaha Sadar','ঝিনাইদহসদর','Dist-32');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-256','256','Kotchandpur','কোটচাঁদপুর','Dist-32');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-257','257','Maheshpur','মহেশপুর','Dist-32');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-258','258','Naldanga','নলডাঙ্গা','Dist-32');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-259','259','Shailakupa','শৈলকুপা','Dist-32');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-26','26','Bhanga','ভাঙ্গা','Dist-2');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-260','260','Alaipur','আলিয়াপুর','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-261','261','Batiaghat','বাতিয়া ঘাট','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-262','262','Chalna Bazar','চালনা বাজার','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-263','263','Digalia','দিগালিয়া','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-264','264','Khulna Sadar','খুলনা সদর','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-265','265','Madinabad','মদিনাবাদ','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-266','266','Paikgachha','পাইকগাছা','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-267','267','Phultala','ফুলতলা','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-268','268','Sajiara','সাজিয়ারা','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-269','269','Terakhada','তেরখাদা','Dist-33');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-27','27','Boalmari','বোয়ালমারী','Dist-2');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-270','270','Bheramara','ভেড়ামারা','Dist-34');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-271','271','Janipur','জনিপুর','Dist-34');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-272','272','Kumarkhali','কুমারখালী','Dist-34');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-273','273','Kustia Sadar','কুষ্টিয়া সদর','Dist-34');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-274','274','Mirpur','মিরপুর','Dist-34');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-275','275','Rafayetpur','রাফায়েতপুর','Dist-34');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-276','276','Arpara','আড়পাড়া','Dist-35');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-277','277','Magura Sadar','মাগুরা সদর','Dist-35');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-278','278','Mohammadpur','মোহাম্মদপুর','Dist-35');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-279','279','Shripur','শ্রিপুর','Dist-35');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-28','28','Charbhadrasan','চরভদ্রাসন','Dist-2');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-280','280','Gangni','গাংনী','Dist-36');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-281','281','Meherpur Sadar','মেহেরপুর সদর','Dist-36');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-282','282','Kalia','কালিয়া','Dist-37');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-283','283','Laxmipasha','লক্ষ্মী পাশা','Dist-37');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-284','284','Mohajan','মহাজান','Dist-37');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-285','285','Narail Sadar','নড়াইল সদর','Dist-37');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-286','286','Ashashuni','আশাশুনির','Dist-38');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-287','287','Debbhata','দেবহাটা','Dist-38');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-288','288','kalaroa','কলারোয়া','Dist-38');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-289','289','Kaliganj UPO','কালীগঞ্জ ইউ পি ও','Dist-38');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-29','29','Faridpur Sadar','ফরিদপুর সদর','Dist-2');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-290','290','Nakipur','নকিপুর','Dist-38');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-291','291','Satkhira Sadar','সাতক্ষীরা সদর','Dist-38');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-292','292','Taala','তালা','Dist-38');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-293','293','Azmireeganj','আজমেরীগঞ্জ','Dist-39');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-294','294','Bahubal','বাহুবল','Dist-39');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-295','295','Baniachang','বানিয়াচং','Dist-39');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-296','296','Chunarughat','চুনারুঘাট','Dist-39');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-297','297','Hobiganj Sadar','হবিগঞ্জসদর','Dist-39');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-298','298','Kalauk','কালাউক','Dist-39');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-299','299','Madhabpur','মাধবপুর','Dist-39');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-3','3','Dhamrai','ধামরাই','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-30','30','Madukhali','মধুখালি','Dist-2');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-300','300','Nabiganj','নবীগঞ্জ','Dist-39');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-301','301','Baralekha','বড়লেখা','Dist-40');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-302','302','Kamalganj','কমলগঞ্জ','Dist-40');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-303','303','Kulaura','কুলাউড়া','Dist-40');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-304','304','Moulvibazar Sadar','মৌলভীবাজার সদর','Dist-40');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-305','305','Rajnagar','রাজনগর','Dist-40');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-306','306','Srimangal','শ্রীমঙ্গল','Dist-40');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-307','307','Bishamsarpur','বিশ্বম্ভরপুর','Dist-41');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-308','308','Chhatak','ছাতক','Dist-41');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-309','309','Dhirai Chandpur','দিরাইচাঁদপুর','Dist-41');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-31','31','Nagarkanda','নগরকান্দা','Dist-2');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-310','310','Duara bazar','দোয়ারাবাজার','Dist-41');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-311','311','Ghungiar','ঘুঙ্গিয়ার','Dist-41');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-312','312','Jagnnathpur','জগন্নাথপুর','Dist-41');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-313','313','Sachna','সাছনা','Dist-41');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-314','314','Sunamganj Sadar','সুনামগঞ্জ সদর','Dist-41');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-315','315','Tahirpur','তাহিরপুর','Dist-41');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-316','316','Balaganj','বালাগঞ্জ','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-317','317','Bianibazar','বিয়ানীবাজারে','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-318','318','Bishwanath','বিশ্বনাথ','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-319','319','Fenchuganj','ফেঞ্চুগঞ্জ','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-32','32','Sadarpur','সদরপুর','Dist-2');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-320','320','Goainhat','গয়াইনহাট','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-321','321','Gopalganj','গোপালগঞ্জ','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-322','322','Jaintapur','জৈন্তাপুর','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-323','323','Jakiganj','জকিগঞ্জ','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-324','324','Kanaighat','কানাইঘাট','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-325','325','Kompanyganj','কোম্পানিগঞ্জ','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-326','326','Sylhet Sadar','সিলেট সদর','Dist-42');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-327','327','Amtali','আমতলী','Dist-43');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-328','328','Bamna','বামনা','Dist-43');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-329','329','Barguna Sadar','বরগুনা সদর','Dist-43');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-33','33','Shriangan','শ্রিয়াঙ্গান','Dist-2');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-330','330','Betagi','বেতাগী','Dist-43');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-331','331','Patharghata','পাথরঘাটা','Dist-43');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-332','332','Agailzhara','আগৈলঝাড়া','Dist-44');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-333','333','Babuganj','বাবুগঞ্জ','Dist-44');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-334','334','Barajalia','বারাজালিয়া','Dist-44');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-335','335','Barishal Sadar','বরিশাল সদর','Dist-44');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-336','336','Gouranadi','গৌরনদী','Dist-44');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-337','337','Mahendiganj','মেহেন্দীগঞ্জ','Dist-44');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-338','338','Muladi','মুলাদী','Dist-44');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-339','339','Sahebganj','সাহেবগঞ্জ','Dist-44');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-34','34','Gazipur Sadar','গাজীপুর সদর','Dist-3');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-340','340','Uzirpur','উজিরপুর','Dist-44');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-341','341','Bhola Sadar','ভোলা সদর','Dist-45');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-342','342','Borhanuddin UPO','বোরহানউদ্দিন ইউ পি ও','Dist-45');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-343','343','Charfashion','চরফ্যাশন','Dist-45');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-344','344','Doulatkhan','দৌলতখান','Dist-45');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-345','345','Hajirhat','হাজিরহাট','Dist-45');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-346','346','Hatshoshiganj','হাতশশিগঞ্জ','Dist-45');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-347','347','Lalmohan UPO','লালমোহন ইউ পি ও','Dist-45');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-348','348','Jhalokathi Sadar','ঝালকাঠি সদর','Dist-46');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-349','349','Kathalia','কাঁঠালিয়া','Dist-46');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-35','35','Kaliakaar','কালিয়াকৈড়','Dist-3');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-350','350','Nalchhiti','নলছিটি','Dist-46');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-351','351','Rajapur','রাজাপুর','Dist-46');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-352','352','Bauphal','বাউফল','Dist-47');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-353','353','Dashmina','দশমিনা','Dist-47');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-354','354','Galachipa','গলাচিপা','Dist-47');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-355','355','Khepupara','খেপুপাড়া','Dist-47');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-356','356','Patuakhali Sadar','পটুয়াখালী সদর','Dist-47');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-357','357','Subidkhali','সুবিদখালি','Dist-47');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-358','358','Banaripara','বানারীপাড়া','Dist-48');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-359','359','Bhandaria','ভান্ডারিয়া','Dist-48');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-36','36','Kaliganj','কালীগঞ্জ','Dist-3');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-360','360','kaukhali','কাউখালী','Dist-48');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-361','361','Mathbaria','মঠবাড়িয়া','Dist-48');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-362','362','Nazirpur','নাজিরপুর','Dist-48');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-363','363','Pirojpur Sadar','পিরোজপুর সদর','Dist-48');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-364','364','Swarupkathi','স্বরূপকাঠি','Dist-48');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-365','365','Alamdighi','আদমদীঘি','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-366','366','Bogra Sadar','বগুড়া সদর','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-367','367','Dhunat','ধুনট','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-368','368','Dupchachia','দুপচাঁচিয়া','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-369','369','Gabtoli','গাবতলী','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-37','37','Kapashia','কাপাশিয়া','Dist-3');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-370','370','Kahalu','কাহালু','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-371','371','Nandigram','নন্দীগ্রাম','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-372','372','Sariakandi','সারিয়াকান্দি','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-373','373','Sherpur','শেরপুর','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-374','374','Shibganj','শিবগঞ্জ','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-375','375','Sonatola','সোনাতলা','Dist-49');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-376','376','Bholahat','ভোলাহাট','Dist-50');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-377','377','Chapinawabganj Sadar','চাঁপাইনবাবগঞ্জসদর','Dist-50');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-378','378','Nachol','নাচল','Dist-50');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-379','379','Rohanpur','রোহনপুর','Dist-50');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-38','38','Monnunagar','মনু নগর','Dist-3');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-380','380','Shibganj U.P.O','শিবগঞ্জ ইউ পি ও','Dist-50');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-381','381','Akkelpur','আক্কেলপুর','Dist-51');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-382','382','Joypurhat Sadar','জয়পুরহাট সদর','Dist-51');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-383','383','kalai','কালাই','Dist-51');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-384','384','Khetlal','ক্ষেতলাল','Dist-51');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-385','385','panchbibi','পাঁচবিবি','Dist-51');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-386','386','Ahsanganj','আসানগঞ্জ','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-387','387','Badalgachhi','বদলগাছী','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-388','388','Dhamuirhat','ধামুইরহাট','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-389','389','Mahadebpur','মহাদেবপুর','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-39','39','Sreepur','শ্রীপুর','Dist-3');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-390','390','Naogaon Sadar','নওগাঁ সদর','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-391','391','Niamatpur','নিয়ামতপুর','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-392','392','Nitpur','নিতপুর','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-393','393','Patnitala','পত্নীতলা','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-394','394','Prasadpur','প্রাসাদপুর','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-395','395','Raninagar','রানীনগর','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-396','396','Sapahar','সাপাহার','Dist-52');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-397','397','Gopalpur UPO','গোপালপুর','Dist-53');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-398','398','Harua','হারুয়া','Dist-53');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-399','399','Hatgurudaspur','হাট গুরুদাসপুর','Dist-53');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-4','4','Dhanmondi','ধানমন্ডি','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-40','40','Sripur','শ্রীপুর','Dist-3');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-400','400','Laxman','লক্ষ্মণ','Dist-53');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-401','401','Natore Sadar','নাটোর সদর','Dist-53');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-402','402','Singra','সিংড়া','Dist-53');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-403','403','Banwarinagar','বানওয়ারি নগর','Dist-54');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-404','404','Bera','বেড়া','Dist-54');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-405','405','Bhangura','ভাঙ্গুরা','Dist-54');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-406','406','Chatmohar','চাটমোহর','Dist-54');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-407','407','Debottar','দেবোত্তর','Dist-54');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-408','408','Ishwardi','ঈশ্বরদী','Dist-54');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-409','409','Pabna Sadar','পাবনা সদর','Dist-54');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-41','41','Gopalganj Sadar','গোপালগঞ্জ সদর','Dist-4');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-410','410','Sathia','সাথিয়া','Dist-54');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-411','411','Sujanagar','সুজানগর','Dist-54');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-412','412','Bagha','বাঘা','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-413','413','Bhabaniganj','ভবানীগঞ্জ','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-414','414','Charghat','চারঘাট','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-415','415','Durgapur','দুর্গাপুর','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-416','416','Godagari','গোদাগাড়ী','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-417','417','Khod Mohanpur','খোদমোহনপুর','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-418','418','Lalitganj','লালিতগঞ্জ','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-419','419','Putia','পুটিয়া','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-42','42','Kashiani','কাশিয়ানী','Dist-4');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-420','420','Rajshahi Sadar','রাজশাহী সদর','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-421','421','Tanor','তানোরে','Dist-55');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-422','422','Baiddya Jam Toil','বৈদ্য জাম তৈল','Dist-56');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-423','423','Belkuchi','বেলকুচি','Dist-56');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-424','424','Dhangora','ধানগর','Dist-56');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-425','425','Kazipur','কাজীপুর','Dist-56');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-426','426','Shahjadpur','শাহজাদপুর','Dist-56');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-427','427','Sirajganj Sadar','সিরাজগঞ্জ সদর','Dist-56');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-428','428','Tarash','তাড়াশ','Dist-56');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-429','429','Ullapara','উল্লাপাড়া','Dist-56');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-43','43','Kotalipara','কোটালীপাড়া','Dist-4');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-430','430','Bangla Hili','বাংলা হিলি','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-431','431','Biral','বিরল','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-432','432','Birampur','বিরামপুর','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-433','433','Birganj','বীরগঞ্জ','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-434','434','Chrirbandar','চিরিরবন্দর','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-435','435','Dinajpur Sadar','দিনাজপুর সদর','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-436','436','Khansama','খানসামা','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-437','437','Maharajganj','মহারাজগঞ্জ','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-438','438','Nababganj','নবাবগঞ্জ জেলায়','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-439','439','Osmanpur','ওসমানপুর','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-44','44','Maksudpur','মকসুদপুর','Dist-4');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-440','440','Parbatipur','পার্বতীপুর','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-441','441','Phulbari','ফুলবাড়ী','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-442','442','Setabganj','শেতাবগঞ্জ','Dist-57');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-443','443','Bonarpara','বনারপারা','Dist-58');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-444','444','Gaibandha Sadar','গাইবান্ধা সদর','Dist-58');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-445','445','Gobindaganj','গোবিন্দগঞ্জ','Dist-58');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-446','446','Palashbari','পলাশবাড়ী','Dist-58');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-447','447','Phulchhari','ফুলছড়ি','Dist-58');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-448','448','Saadullapur','সাদ্যুলাপুর','Dist-58');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-449','449','Sundarganj','সুন্দরগঞ্জ','Dist-58');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-45','45','Tungipara','টুঙ্গিপাড়া','Dist-4');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-450','450','Bhurungamari','ভুরুঙ্গামারী','Dist-59');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-451','451','Chilmari','চিলমারী','Dist-59');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-452','452','Kurigram Sadar','কুড়িগ্রাম সদর','Dist-59');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-453','453','Nageshwar','নাগেশ্বরী','Dist-59');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-454','454','Rajarhat','রাজারহাট','Dist-59');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-455','455','Rajibpur','রাজিবপুর','Dist-59');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-456','456','Roumari','রৌমারী','Dist-59');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-457','457','Ulipur','উলিপুর','Dist-59');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-458','458','Aditmari','আদিতমারী','Dist-60');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-459','459','Hatibandha','হাতীবান্ধা','Dist-60');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-46','46','Dewangonj','দেয়ানগঞ্জ','Dist-5');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-460','460','Lalmonirhat Sadar','লালমনিরহাট সদর','Dist-60');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-461','461','Patgram','পাটগ্রাম','Dist-60');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-462','462','Tushbhandar','তুশভান্দার','Dist-60');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-463','463','Dimla','ডিমলা','Dist-61');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-464','464','Domar','ডোমার','Dist-61');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-465','465','Jaldhaka','জলঢাকা','Dist-61');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-466','466','Kishoriganj','কিশোরগঞ্জ','Dist-61');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-467','467','Nilphamari Sadar','নীলফামারী সদর','Dist-61');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-468','468','Syedpur','সৈয়দপুর','Dist-61');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-469','469','Boda','বোদা','Dist-62');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-47','47','Islampur','ইসলামপুর','Dist-5');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-470','470','Chotto Dab','ছট্টো দাব','Dist-62');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-471','471','Dabiganj','দেবীগঞ্জ','Dist-62');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-472','472','Panchagra Sadar','পঞ্চগড়সদর','Dist-62');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-473','473','Tetulia','তেঁতুলিয়া','Dist-62');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-474','474','Badarganj','বদরগঞ্জ','Dist-63');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-475','475','Gangachara','গঙ্গাচড়া','Dist-63');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-476','476','Kaunia','কাউনিয়া','Dist-63');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-477','477','Mithapukur','মিঠাপুকুর','Dist-63');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-478','478','Pirgachha','পীরগাছা','Dist-63');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-479','479','Rangpur Sadar','রংপুর সদর','Dist-63');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-48','48','Jamalpur','জামালপুর','Dist-5');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-480','480','Taraganj','তারাগঞ্জ','Dist-63');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-481','481','Baliadangi','বালিয়াডাঙ্গী','Dist-64');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-482','482','Jibanpur','জীবনপুর','Dist-64');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-483','483','Pirganj','পীরগঞ্জ','Dist-64');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-484','484','Rani Sankail','রাণীশংকৈল','Dist-64');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-485','485','Thakurgaon Sadar','ঠাকুরগাঁও সদর','Dist-64');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-49','49','Malandah','মেলান্দহ','Dist-5');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-5','5','Gulshan','গুলশান','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-50','50','Mathargonj','মাদারগঞ্জ','Dist-5');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-51','51','Shorishabari','সরিষাবাড়ী','Dist-5');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-52','52','Bajitpur','বাজিতপুর','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-53','53','Bhairob','ভৈরব','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-54','54','Hossenpur','হোসেনপুর','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-55','55','Itna','ইটনা','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-56','56','Karimganj','করিমগঞ্জ','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-57','57','Katiadi','কটিয়াদি','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-58','58','Kishoreganj Sadar','কিশোরগঞ্জ সদর','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-59','59','Kuliarchar','কুলিয়ারচর','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-6','6','Jatrabari','যাত্রাবাড়ি','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-60','60','Mithamoin','মিঠামইন','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-61','61','Nikli','নিকলী','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-62','62','Ostagram','অস্টগ্রাম','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-63','63','Pakundia','পাকুন্দিয়া','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-64','64','Tarial','তাড়াইল','Dist-6');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-65','65','Barhamganj','বারহামগঞ্জ','Dist-7');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-66','66','kalkini','কালকিনি','Dist-7');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-67','67','Madaripur Sadar','মাদারীপুর সদর','Dist-7');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-68','68','Rajoir','রাজৈর','Dist-7');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-69','69','Doulatpur','দৌলতপুর','Dist-8');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-7','7','Joypara','জয়পারা','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-70','70','Gheor','গিওর','Dist-8');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-71','71','Lechhraganj','লেছহ্রাগঞ্জ','Dist-8');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-72','72','Manikganj Sadar','মানিকগঞ্জ সদর','Dist-8');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-73','73','Saturia','সাটুরিয়া','Dist-8');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-74','74','Shibloya','শিবালয়','Dist-8');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-75','75','Singari','সিংগাইর','Dist-8');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-76','76','Gajaria','গজারিয়া','Dist-9');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-77','77','Lohajong','লৌহজং','Dist-9');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-78','78','Munshiganj Sadar','মুন্সীগঞ্জ সদর','Dist-9');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-79','79','Sirajdikhan','সিরাজদিখান','Dist-9');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-8','8','Keraniganj','কেরানীগঞ্জ','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-80','80','Srinagar','শ্রীনগর','Dist-9');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-81','81','Tangibari','টঙ্গিবাড়ী','Dist-9');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-82','82','Bhaluka','ভালুকা','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-83','83','Fulbaria','ফুলবাড়িয়া','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-84','84','Gaforgaon','গফরগাঁও','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-85','85','Gouripur','গৌরীপুর','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-86','86','Haluaghat','হালুয়াঘাট','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-87','87','Isshwargonj','ঈশ্বরগঞ্জ','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-88','88','Muktagachha','মুক্তাগাছা','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-89','89','Mymensingh Sadar','ময়মনসিংহ সদর','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-9','9','Khilgaon','খিলগাঁও','Dist-1');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-90','90','Nandail','নান্দাইল','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-91','91','Phulpur','ফুলপুর','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-92','92','Trishal','ত্রিশাল','Dist-10');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-93','93','Araihazar','আড়াইহাজার','Dist-11');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-94','94','Baidder Bazar','বাঈদার বাজার','Dist-11');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-95','95','Bandar','বাঁদর','Dist-11');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-96','96','Fatullah','ফতুল্লা','Dist-11');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-97','97','Narayanganj Sadar','নারায়ণগঞ্জ সদর','Dist-11');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-98','98','Rupganj','রূপগঞ্জ','Dist-11');
insert into thana (oid, thana_code, name_en, name_bn, district_oid) values ('Thana-99','99','Siddirganj','সিদ্ধিরগঞ্জ','Dist-11');
commit;
