-- country
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_001','Afghanistan','Kabul','93','+93','AF','AFG');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_002','Albania','Tirana','355','+355','AL','ALB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_003','Algeria','Algiers','213','+213','DZ','DZA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_004','American Samoa',null,'1-684','+1-684','AS','ASM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_005','Andorra','Andorra la Vella','376','+376','AD','AND');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_006','Angola','Luanda','244','+244','AO','AGO');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_007','Anguilla',null,'1-264','+1-264','AI','AIA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_008','Antarctica',null,'672','+672','AQ','ATA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_009','Antigua and Barbuda','Saint Johns','1-268','+1-268','AG','ATG');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_010','Argentina','Buenos Aires','54','+54','AR','ARG');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_011','Armenia','Yerevan','374','+374','AM','ARM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_012','Aruba',null,'297','+297','AW','ABW');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_013','Australia','Canberra','61','+61','AU','AUS');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_014','Austria','Vienna','43','+43','AT','AUT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_015','Azerbaijan','Baku','994','+994','AZ','AZE');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_016','Bahamas','Nassau','1-242','+1-242','BS','BHS');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_017','Bahrain','Manama','973','+973','BH','BHR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_018','Bangladesh','Dhaka','880','+880','BD','BGD');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_019','Barbados','Bridgetown','1-246','+1-246','BB','BRB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_020','Belarus','Minsk','375','+375','BY','BLR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_021','Belgium','Brussels','32','+32','BE','BEL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_022','Belize','Belmopan','501','+501','BZ','BLZ');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_023','Benin','Porto-Novo','229','+229','BJ','BEN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_024','Bermuda',null,'1-441','+1-441','BM','BMU');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_025','Bhutan','Thimphu','975','+975','BT','BTN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_026','Bolivia','Sucre (de jure), La Paz (seat of government)','591','+591','BO','BOL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_027','Bosnia and Herzegovina','Sarajevo','387','+387','BA','BIH');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_028','Botswana','Gaborone','267','+267','BW','BWA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_029','Brazil','Brasilia','55','+55','BR','BRA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_030','British Indian Ocean Territory',null,'246','+246','IO','IOT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_031','British Virgin Islands',null,'1-284','+1-284','VG','VGB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_032','Brunei','Bandar Seri Begawan','673','+673','BN','BRN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_033','Bulgaria','Sofia','359','+359','BG','BGR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_034','Burkina Faso','Ouagadougou','226','+226','BF','BFA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_035','Myanmar',null,'95','+95','MM','MMR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_036','Burundi','Gitega','257','+257','BI','BDI');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_037','Cambodia',null,'855','+855','KH','KHM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_038','Cameroon',null,'237','+237','CM','CMR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_039','Canada',null,'1','+1','CA','CAN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_040','Cape Verde',null,'238','+238','CV','CPV');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_041','Cayman Islands',null,'1-345','+1-345','KY','CYM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_042','Central African Republic',null,'236','+236','CF','CAF');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_043','Chad',null,'235','+235','TD','TCD');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_044','Chile',null,'56','+56','CL','CHL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_045','China',null,'86','+86','CN','CHN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_046','Christmas Island',null,'61','+61','CX','CXR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_047','Cocos Islands',null,'61','+61','CC','CCK');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_048','Colombia',null,'57','+57','CO','COL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_049','Comoros',null,'269','+269','KM','COM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_050','Republic of the Congo',null,'242','+242','CG','COG');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_051','Democratic Republic of the C',null,'243','+243','CD','COD');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_052','Cook Islands',null,'682','+682','CK','COK');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_053','Costa Rica',null,'506','+506','CR','CRI');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_054','Croatia',null,'385','+385','HR','HRV');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_055','Cuba',null,'53','+53','CU','CUB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_056','Curacao',null,'599','+599','CW','CUW');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_057','Cyprus',null,'357','+357','CY','CYP');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_058','Czech Republic',null,'420','+420','CZ','CZE');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_059','Denmark',null,'45','+45','DK','DNK');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_060','Djibouti',null,'253','+253','DJ','DJI');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_061','Dominica',null,'1-767','+1-767','DM','DMA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_062','Dominican Republic',null,'1-809, 1-829, 1-8','+1-809, 1-829, 1-8','DO','DOM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_063','East Timor',null,'670','+670','TL','TLS');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_064','Ecuador',null,'593','+593','EC','ECU');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_065','Egypt',null,'20','+20','EG','EGY');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_066','El Salvador',null,'503','+503','SV','SLV');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_067','Equatorial Guinea',null,'240','+240','GQ','GNQ');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_068','Eritrea',null,'291','+291','ER','ERI');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_069','Estonia',null,'372','+372','EE','EST');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_070','Ethiopia',null,'251','+251','ET','ETH');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_071','Falkland Islands',null,'500','+500','FK','FLK');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_072','Faroe Islands',null,'298','+298','FO','FRO');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_073','Fiji',null,'679','+679','FJ','FJI');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_074','Finland',null,'358','+358','FI','FIN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_075','France',null,'33','+33','FR','FRA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_076','French Polynesia',null,'689','+689','PF','PYF');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_077','Gabon',null,'241','+241','GA','GAB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_078','Gambia',null,'220','+220','GM','GMB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_079','Georgia',null,'995','+995','GE','GEO');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_080','Germany',null,'49','+49','DE','DEU');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_081','Ghana',null,'233','+233','GH','GHA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_082','Gibraltar',null,'350','+350','GI','GIB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_083','Greece',null,'30','+30','GR','GRC');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_084','Greenland',null,'299','+299','GL','GRL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_085','Grenada',null,'1-473','+1-473','GD','GRD');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_086','Guam',null,'1-671','+1-671','GU','GUM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_087','Guatemala',null,'502','+502','GT','GTM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_088','Guernsey',null,'44-1481','+44-1481','GG','GGY');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_089','Guinea',null,'224','+224','GN','GIN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_090','Guinea-Bissau',null,'245','+245','GW','GNB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_091','Guyana',null,'592','+592','GY','GUY');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_092','Haiti',null,'509','+509','HT','HTI');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_093','Honduras',null,'504','+504','HN','HND');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_094','Hong Kong',null,'852','+852','HK','HKG');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_095','Hungary',null,'36','+36','HU','HUN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_096','Iceland',null,'354','+354','IS','ISL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_097','India',null,'91','+91','IN','IND');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_098','Indonesia',null,'62','+62','ID','IDN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_099','Iran',null,'98','+98','IR','IRN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_100','Iraq',null,'964','+964','IQ','IRQ');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_101','Ireland',null,'353','+353','IE','IRL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_102','Isle of Man',null,'44-1624','+44-1624','IM','IMN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_103','Israel',null,'972','+972','IL','ISR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_104','Italy',null,'39','+39','IT','ITA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_105','Ivory Coast',null,'225','+225','CI','CIV');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_106','Jamaica',null,'1-876','+1-876','JM','JAM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_107','Japan',null,'81','+81','JP','JPN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_108','Jersey',null,'44-1534','+44-1534','JE','JEY');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_109','Jordan',null,'962','+962','JO','JOR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_110','Kazakhstan',null,'7','+7','KZ','KAZ');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_111','Kenya',null,'254','+254','KE','KEN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_112','Kiribati',null,'686','+686','KI','KIR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_113','Kosovo',null,'383','+383','XK','XKX');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_114','Kuwait',null,'965','+965','KW','KWT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_115','Kyrgyzstan',null,'996','+996','KG','KGZ');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_116','Laos',null,'856','+856','LA','LAO');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_117','Latvia',null,'371','+371','LV','LVA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_118','Lebanon',null,'961','+961','LB','LBN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_119','Lesotho',null,'266','+266','LS','LSO');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_120','Liberia',null,'231','+231','LR','LBR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_121','Libya',null,'218','+218','LY','LBY');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_122','Liechtenstein',null,'423','+423','LI','LIE');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_123','Lithuania',null,'370','+370','LT','LTU');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_124','Luxembourg',null,'352','+352','LU','LUX');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_125','Macau',null,'853','+853','MO','MAC');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_126','Macedonia',null,'389','+389','MK','MKD');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_127','Madagascar',null,'261','+261','MG','MDG');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_128','Malawi',null,'265','+265','MW','MWI');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_129','Malaysia',null,'60','+60','MY','MYS');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_130','Maldives',null,'960','+960','MV','MDV');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_131','Mali',null,'223','+223','ML','MLI');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_132','Malta',null,'356','+356','MT','MLT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_133','Marshall Islands',null,'692','+692','MH','MHL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_134','Mauritania',null,'222','+222','MR','MRT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_135','Mauritius',null,'230','+230','MU','MUS');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_136','Mayotte',null,'262','+262','YT','MYT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_137','Mexico',null,'52','+52','MX','MEX');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_138','Micronesia',null,'691','+691','FM','FSM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_139','Moldova',null,'373','+373','MD','MDA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_140','Monaco',null,'377','+377','MC','MCO');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_141','Mongolia',null,'976','+976','MN','MNG');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_142','Montenegro',null,'382','+382','ME','MNE');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_143','Montserrat',null,'1-664','+1-664','MS','MSR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_144','Morocco',null,'212','+212','MA','MAR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_145','Mozambique',null,'258','+258','MZ','MOZ');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_146','Namibia',null,'264','+264','NA','NAM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_147','Nauru',null,'674','+674','NR
','NRU
');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_148','Nepal',null,'977','+977','NP','NPL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_149','Netherlands',null,'31','+31','NL','NLD');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_150','Netherlands Antilles',null,'599','+599','AN','ANT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_151','New Caledonia',null,'687','+687','NC','NCL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_152','New Zealand',null,'64','+64','NZ','NZL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_153','Nicaragua',null,'505','+505','NI','NIC');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_154','Niger',null,'227','+227','NE','NER');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_155','Nigeria',null,'234','+234','NG','NGA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_156','Niue',null,'683','+683','NU','NIU');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_157','Northern Mariana Islands',null,'1-670','+1-670','MP','MNP');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_158','North Korea',null,'850','+850','KP','PRK');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_159','Norway',null,'47','+47','NO','NOR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_160','Oman',null,'968','+968','OM','OMN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_161','Pakistan',null,'92','+92','PK','PAK');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_162','Palau',null,'680','+680','PW','PLW');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_163','Palestine',null,'970','+970','PS','PSE');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_164','Panama',null,'507','+507','PA','PAN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_165','Papua New Guinea',null,'675','+675','PG','PNG');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_166','Paraguay',null,'595','+595','PY','PRY');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_167','Peru',null,'51','+51','PE','PER');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_168','Philippines',null,'63','+63','PH','PHL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_169','Pitcairn',null,'64','+64','PN','PCN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_170','Poland',null,'48','+48','PL','POL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_171','Portugal',null,'351','+351','PT','PRT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_172','Puerto Rico',null,'1-787, 1-939','+1-787, 1-939','PR','PRI');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_173','Qatar',null,'974','+974','QA','QAT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_174','Reunion',null,'262','+262','RE','REU');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_175','Romania',null,'40','+40','RO','ROU');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_176','Russia',null,'7','+7','RU','RUS');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_177','Rwanda',null,'250','+250','RW','RWA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_178','Saint Barthelemy',null,'590','+590','BL','BLM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_179','Samoa',null,'685','+685','WS','WSM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_180','San Marino',null,'378','+378','SM','SMR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_181','Sao Tome and Principe',null,'239','+239','ST','STP');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_182','Saudi Arabia',null,'966','+966','SA','SAU');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_183','Senegal',null,'221','+221','SN','SEN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_184','Serbia',null,'381','+381','RS','SRB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_185','Seychelles',null,'248','+248','SC','SYC');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_186','Sierra Leone',null,'232','+232','SL','SLE');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_187','Singapore',null,'65','+65','SG','SGP');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_188','Sint Maarten',null,'1-721','+1-721','SX','SXM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_189','Slovakia',null,'421','+421','SK','SVK');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_190','Slovenia',null,'386','+386','SI','SVN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_191','Solomon Islands',null,'677','+677','SB','SLB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_192','Somalia',null,'252','+252','SO','SOM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_193','South Africa',null,'27','+27','ZA','ZAF');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_194','South Korea',null,'82','+82','KR','KOR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_195','South Sudan',null,'211','+211','SS','SSD');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_196','Spain',null,'34','+34','ES','ESP');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_197','Sri Lanka',null,'94','+94','LK','LKA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_198','Saint Helena',null,'290','+290','SH','SHN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_199','Saint Kitts and Nevis',null,'1-869','+1-869','KN','KNA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_200','Saint Lucia',null,'1-758','+1-758','LC','LCA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_201','Saint Martin',null,'590','+590','MF','MAF');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_202','Saint Pierre and Miquelon',null,'508','+508','PM','SPM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_203','Saint Vincent and the Grenadi',null,'1-784','+1-784','VC','VCT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_204','Sudan',null,'249','+249','SD','SDN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_205','Suriname',null,'597','+597','SR','SUR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_206','Svalbard and Jan Mayen',null,'47','+47','SJ','SJM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_207','Swaziland',null,'268','+268','SZ','SWZ');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_208','Sweden',null,'46','+46','SE','SWE');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_209','Switzerland',null,'41','+41','CH','CHE');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_210','Syria',null,'963','+963','SY','SYR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_211','Taiwan',null,'886','+886','TW','TWN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_212','Tajikistan',null,'992','+992','TJ','TJK');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_213','Tanzania',null,'255','+255','TZ','TZA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_214','Thailand',null,'66','+66','TH','THA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_215','Togo',null,'228','+228','TG','TGO');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_216','Tokelau',null,'690','+690','TK','TKL');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_217','Tonga',null,'676','+676','TO','TON');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_218','Trinidad and Tobago',null,'1-868','+1-868','TT','TTO');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_219','Tunisia',null,'216','+216','TN','TUN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_220','Turkey',null,'90','+90','TR','TUR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_221','Turkmenistan',null,'993','+993','TM','TKM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_222','Turks and Caicos Islands',null,'1-649','+1-649','TC','TCA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_223','Tuvalu',null,'688','+688','TV','TUV');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_224','United Arab Emirates',null,'971','+971','AE','ARE');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_225','Uganda',null,'256','+256','UG','UGA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_226','United Kingdom',null,'44','+44','GB','GBR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_227','Ukraine',null,'380','+380','UA','UKR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_228','Uruguay',null,'598','+598','UY','URY');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_229','United States',null,'1','+1','US','USA');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_230','Uzbekistan',null,'998','+998','UZ','UZB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_231','Vanuatu',null,'678','+678','VU','VUT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_232','Vatican',null,'379','+379','VA','VAT');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_233','Venezuela',null,'58','+58','VE','VEN');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_234','Vietnam',null,'84','+84','VN','VNM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_235','U.S. Virgin Islands',null,'1-340','+1-340','VI','VIR');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_236','Wallis and Futuna',null,'681','+681','WF','WLF');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_237','Western Sahara',null,'212','+212','EH','ESH');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_238','Yemen',null,'967','+967','YE','YEM');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_239','Zambia',null,'260','+260','ZM','ZMB');
insert into country (oid, name, capital, country_code, dialing_code, iso_code_alpha_two, iso_code_alpha_three) values ('country_240','Zimbabwe',null,'263','+263','ZW','ZWE');
