-- bank
insert into bank (oid, name_en, name_bn) values ('Bank-1001','AB Bank Limited','এবি ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1002','Agrani Bank Limited','অগ্রণী ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1003','Al-Arafah Islami Bank Limited','আল-আরাফাহ ইসলামী ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1004','Bangladesh Commerce Bank Limited','বাংলাদেশ কমার্স ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1005','Bangladesh Development Bank Limited','বাংলাদেশ উন্নয়ন ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1006','Bangladesh Krishi Bank','বাংলাদেশ কৃষি ব্যাংক');
insert into bank (oid, name_en, name_bn) values ('Bank-1007','Bank Al-Falah Limited','ব্যাংক আল-ফালাহ লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1008','Bank Asia Limited','ব্যাংক এশিয়া লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1009','BASIC Bank Limited','বেসিক ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1010','BRAC Bank Limited','ব্র্যাক ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1011','Citibank N.A','সিটি ব্যাংক এন.এ.');
insert into bank (oid, name_en, name_bn) values ('Bank-1012','Commercial Bank of Ceylon Limited','বাণিজ্যিক ব্যাংক অফ সিলন লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1013','Community Bank Bangladesh Limited','কমিউনিটি ব্যাংক বাংলাদেশ লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1014','Dhaka Bank Limited','ঢাকা ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1015','Dutch-Bangla Bank Limited','ডাচ-বাংলা ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1016','Eastern Bank Limited','ইস্টার্ন ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1017','EXIM Bank Limited','এক্সিম ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1018','First Security Islami Bank Limited','ফার্স্ট সিকিউরিটি ইসলামী ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1019','Habib Bank Ltd.','হাবিব ব্যাংক লি');
insert into bank (oid, name_en, name_bn) values ('Bank-1020','ICB Islamic Bank Ltd.','আইসিবি ইসলামিক ব্যাংক লি');
insert into bank (oid, name_en, name_bn) values ('Bank-1021','IFIC Bank Limited','আইএফআইসি ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1022','Islami Bank Bangladesh Ltd','ইসলামী ব্যাংক বাংলাদেশ লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1023','Jamuna Bank Ltd','যমুনা ব্যাংক লি');
insert into bank (oid, name_en, name_bn) values ('Bank-1024','Janata Bank Limited','জনতা ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1025','Meghna Bank Limited','মেঘনা ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1026','Mercantile Bank Limited','মার্কেন্টাইল ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1027','Midland Bank Limited','মিডল্যান্ড ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1028','Modhumoti Bank Ltd.','মধুমতি ব্যাংক লি');
insert into bank (oid, name_en, name_bn) values ('Bank-1029','Mutual Trust Bank Limited','মিউচুয়াল ট্রাস্ট ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1030','National Bank Limited','ন্যাশনাল ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1031','National Bank of Pakistan','ন্যাশনাল ব্যাংক অফ পাকিস্তান');
insert into bank (oid, name_en, name_bn) values ('Bank-1032','National Credit & Commerce Bank Ltd','ন্যাশনাল ক্রেডিট অ্যান্ড কমার্স ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1033','NRB Bank Limited','এনআরবি ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1034','NRB Commercial Bank Limited','এনআরবি বাণিজ্যিক ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1035','NRB Global Bank Limited','এনআরবি গ্লোবাল ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1036','One Bank Limited','ওয়ান ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1037','Padma Bank Limited','পদ্মা ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1038','Premier Bank Limited','প্রিমিয়ার ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1039','Prime Bank Ltd','প্রাইম ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1040','Probashi Kollyan Bank','প্রবাসী কল্যাণ ব্যাংক');
insert into bank (oid, name_en, name_bn) values ('Bank-1041','Pubali Bank Limited','পূবালী ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1042','Rajshahi Krishi Unnayan Bank','রাজশাহী কৃষি উন্নয়ন ব্যাংক');
insert into bank (oid, name_en, name_bn) values ('Bank-1043','Rupali Bank Limited','রূপালী ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1044','Shahjalal Islami Bank Limited','শাহজালাল ইসলামী ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1045','Shimanto Bank Limited','সীমান্ত ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1046','Social Islami Bank Ltd.','সোশ্যাল ইসলামী ব্যাংক লি');
insert into bank (oid, name_en, name_bn) values ('Bank-1047','Sonali Bank Limited','সোনালী ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1048','South Bangla Agriculture & Commerce Bank Limited','সাউথ বাংলা কৃষি ও বাণিজ্য ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1049','Southeast Bank Limited','সাউথ ইস্ট ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1050','Standard Bank Limited','স্ট্যান্ডার্ড ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1051','Standard Chartered Bank','স্ট্যান্ডার্ড চার্টার্ড ব্যাংক');
insert into bank (oid, name_en, name_bn) values ('Bank-1052','State Bank of India','স্টেট ব্যাংক অফ ইন্ডিয়া');
insert into bank (oid, name_en, name_bn) values ('Bank-1053','The City Bank Ltd.','সিটি ব্যাংক লি');
insert into bank (oid, name_en, name_bn) values ('Bank-1054','The Hong Kong and Shanghai Banking Corporation. Ltd.','হংকং এবং সাংহাই ব্যাংকিং কর্পোরেশন লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1055','Trust Bank Limited','ট্রাস্ট ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1056','Union Bank Limited','ইউনিয়ন ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1057','United Commercial Bank Limited','ইউনাইটেড কমার্শিয়াল ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1058','Uttara Bank Limited','উত্তরা ব্যাংক লিমিটেড');
insert into bank (oid, name_en, name_bn) values ('Bank-1059','Woori Bank','উওরি ব্যাংক');
insert into bank (oid, name_en, name_bn) values ('Bank-1060','Ansar VDP Unnayan Bank','আনসার ভিডিপি আনয়ন ব্যাংক');
insert into bank (oid, name_en, name_bn) values ('Bank-1061','Jubilee Bank','জুবিলী ব্যাংক');
insert into bank (oid, name_en, name_bn) values ('Bank-1062','Karmashangosthan Bank','কর্মসংস্থান ব্যাংক');
insert into bank (oid, name_en, name_bn) values ('Bank-1063','Palli Sanchay Bank','পল্লী সঞ্চয় ব্যাংক');
